spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/NotZed77/ecommerce-config-server
          username: NotZed77
          password: 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
          default-label: main
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

server:
  port: 8888